BATTERY_ITEM_NAMES = [
    "Battery Status",
    "Battery Power",
    "Battery Discharging Power",
    "Battery Capacity",
    "SoC",
    "SoH",
    "Total Charging Energy",
    "Total Discharging Energy",
    "Daily Charging Energy",
    "Daily Discharging Energy",
    "Charge Source",
    "Pack RT Current",
    "Pack RT Alarm State",
    "Pack RT Fault State",
    "Pack RT Temperature Env",
    "Pack RT Balance State",
    "Pack RT FullCharge Capacity",
    "Pack RT Remaining Capacity",
    "Pack RT Temperature1 Pack",
    "Pack RT Temperature2 Pack",
    "Pack RT Temperature3 Pack",
    "Pack RT Temperature4 Pack",
    "Pack RT Cycles",
    "Pack Fault Current",
    "Pack Fault State",
    "Pack Fault Temperature Env",
    "Pack Fault FullCharge Capacity",
    "Pack Fault Remaining Capacity",
    "Pack Fault Temperature1 Pack",
    "Pack Fault Temperature2 Pack",
    "Pack Fault Temperature3 Pack",
    "Pack Fault Temperature4 Pack",
    "Power- Battery Pack 1",
    "Total Voltage- Battery Pack 1",
    "Current- Battery Pack 1",
    "SoC- Battery Pack 1",
    "Soh-Battery Pack1",
    "Cycle Times-Battery Pack1",
    "Temperature- Battery Pack 1",
]

CONSUMPTION_ITEM_NAMES = [
    "Total Consumption Power",
    "Cumulative Consumption",
    "Daily Consumption",
]

GRID_ITEM_NAMES = [
    "Leak Current",
    "Insulation Impedance 1",
    "NBUS Voltage",
    "Grid Status",
    "Grid Frequency",
    "Total Grid Power",
    "Cumulative Grid Feed-in",
    "Cumulative Energy Purchased",
    "Daily Grid Feed-in",
    "Daily Energy Purchased",
]

PRODUCTION_ITEM_NAMES = [
    "DC Voltage PV1",
    "DC Voltage PV2",
    "DC Current PV1",
    "DC Current PV2",
    "DC Power PV1",
    "DC Power PV2",
    "AC Voltage R/U/A",
    "AC Voltage S/V/B",
    "AC Voltage T/W/C",
    "AC Current R/U/A",
    "AC Current S/V/B",
    "AC Current T/W/C",
    "AC Output Frequency R",
    "Total AC Output Power",
    "Output Voltage Off-grid--R phase",
    "Output Voltage Off-grid--S phase",
    "Output Voltage Off-grid--T phase",
    "Cumulative Production (Active)",
    "Daily Production (Active)",
    "ActivePower PV Ext",
    "Dc Component- Phase R Current",
    "Dc Component- Phase S Current",
    "Dc Component- Phase T Current",
    "Dc Component- Phase R Voltage",
    "Dc Component- Phase S Voltage",
    "Dc Component- Phase T Voltage",
    "Load Active Power",
    "Total Reactive Power",
    "R-Phase Load Rctive Power",
    "Active Power Of S-Phase Load",
    "T-Phase Load Active Power",
    "PCC AC Current R",
    "PCC AC Current S",
    "PCC AC Current T",
    "PCC AC Power R",
    "PCC AC Power S",
    "PCC AC Power T",
    "PCU_DC_High_Voltage",
    "PCU_DC_Low_Voltage",
    "PCU_Low_Current",
    "PCU_Low_Power",
    "PCU_BusP",
    "PCU_BusN",
    "PCU_FC_Voltage1",
    "PCU_FC_Voltage2",
    "PCU_FC_Voltage3",
    "PCU_FC_Voltage4",
    "PCU_Max_Charge_Current",
    "PCU_Max_Discharge_Current",
]

TEMPERATURE_ITEM_NAMES = [
    "Module temperature1",
    "Single Plate Ambient Temperature",
    "Radiator Temperature 1",
    "Cell Average Temperature",
]